package sctp

/*
	#include<sys/socket.h>
	#include<stdint.h>
	#include<linux/sctp.h>
*/
import "C"
import (
	"fmt"

	syscall "golang.org/x/sys/unix"
)

const (
	SOL_SCTP = 132

	SCTP_BINDX_ADD_ADDR = 0x01
	SCTP_BINDX_REM_ADDR = 0x02

	MSG_NOTIFICATION = C.MSG_NOTIFICATION
	MSG_EOR          = C.MSG_EOR
)

const (
	SCTP_RTOINFO = iota
	SCTP_ASSOCINFO
	SCTP_INITMSG
	SCTP_NODELAY
	SCTP_AUTOCLOSE
	SCTP_SET_PEER_PRIMARY_ADDR
	SCTP_PRIMARY_ADDR
	SCTP_ADAPTATION_LAYER
	SCTP_DISABLE_FRAGMENTS
	SCTP_PEER_ADDR_PARAMS
	SCTP_DEFAULT_SENT_PARAM
	SCTP_EVENTS
	SCTP_I_WANT_MAPPED_V4_ADDR
	SCTP_MAXSEG
	SCTP_STATUS
	SCTP_GET_PEER_ADDR_INFO
	SCTP_DELAYED_ACK_TIME
	SCTP_DELAYED_ACK  = SCTP_DELAYED_ACK_TIME
	SCTP_DELAYED_SACK = SCTP_DELAYED_ACK_TIME

	SCTP_SOCKOPT_BINDX_ADD = 100
	SCTP_SOCKOPT_BINDX_REM = 101
	SCTP_SOCKOPT_PEELOFF   = 102
	SCTP_GET_PEER_ADDRS    = 108
	SCTP_GET_LOCAL_ADDRS   = 109
	SCTP_SOCKOPT_CONNECTX  = 110
	SCTP_SOCKOPT_CONNECTX3 = 111
)

const (
	SCTP_EVENT_DATA_IO = 1 << iota
	SCTP_EVENT_ASSOCIATION
	SCTP_EVENT_ADDRESS
	SCTP_EVENT_SEND_FAILURE
	SCTP_EVENT_PEER_ERROR
	SCTP_EVENT_SHUTDOWN
	SCTP_EVENT_PARTIAL_DELIVERY
	SCTP_EVENT_ADAPTATION_LAYER
	SCTP_EVENT_AUTHENTICATION
	SCTP_EVENT_SENDER_DRY

	SCTP_EVENT_ALL = SCTP_EVENT_DATA_IO | SCTP_EVENT_ASSOCIATION | SCTP_EVENT_ADDRESS | SCTP_EVENT_SEND_FAILURE | SCTP_EVENT_PEER_ERROR | SCTP_EVENT_SHUTDOWN | SCTP_EVENT_PARTIAL_DELIVERY | SCTP_EVENT_ADAPTATION_LAYER | SCTP_EVENT_AUTHENTICATION | SCTP_EVENT_SENDER_DRY
)

type SCTPNotificationType uint16

const (
	SCTP_SN_TYPE_BASE = SCTPNotificationType(iota + (1 << 15))
	SCTP_ASSOC_CHANGE
	SCTP_PEER_ADDR_CHANGE
	SCTP_SEND_FAILED
	SCTP_REMOTE_ERROR
	SCTP_SHUTDOWN_EVENT
	SCTP_PARTIAL_DELIVERY_EVENT
	SCTP_ADAPTATION_INDICATION
	SCTP_AUTHENTICATION_INDICATION
	SCTP_SENDER_DRY_EVENT
)

func (n SCTPNotificationType) String() string {
	switch n {
	case SCTP_ASSOC_CHANGE:
		return "SCTP_ASSOC_CHANGE"
	case SCTP_PEER_ADDR_CHANGE:
		return "SCTP_PEER_ADDR_CHANGE"
	case SCTP_SEND_FAILED:
		return "SCTP_SEND_FAILED"
	case SCTP_REMOTE_ERROR:
		return "SCTP_REMOTE_ERROR"
	case SCTP_SHUTDOWN_EVENT:
		return "SCTP_SHUTDOWN_EVENT"
	case SCTP_PARTIAL_DELIVERY_EVENT:
		return "SCTP_PARTIAL_DELIVERY_EVENT"
	case SCTP_ADAPTATION_INDICATION:
		return "SCTP_ADAPTATION_INDICATION"
	case SCTP_AUTHENTICATION_INDICATION:
		return "SCTP_AUTHENTICATION_INDICATION"
	case SCTP_SENDER_DRY_EVENT:
		return "SCTP_SENDER_DRY_EVENT"
	default:
		panic(fmt.Sprintf("Unknown notification type: %d", n))
	}
}

type SCTPCmsgType int32

func (t SCTPCmsgType) i32() int32 { return int32(t) }

const (
	SCTP_CMSG_INIT = SCTPCmsgType(iota)
	SCTP_CMSG_SNDRCV
	SCTP_CMSG_SNDINFO
	SCTP_CMSG_RCVINFO
	SCTP_CMSG_NXTINFO
)

const (
	SCTP_UNORDERED = 1 << iota
	SCTP_ADDR_OVER
	SCTP_ABORT
	SCTP_SACK_IMMEDIATELY
	SCTP_EOF
)

const (
	SCTP_MAX_STREAM = 0xffff
)

type SCTPState uint16

const (
	SCTP_COMM_UP = SCTPState(iota)
	SCTP_COMM_LOST
	SCTP_RESTART
	SCTP_SHUTDOWN_COMP
	SCTP_CANT_STR_ASSOC
)

func (s SCTPState) String() string {
	switch s {
	case SCTP_COMM_UP:
		return "SCTP_COMM_UP"
	case SCTP_COMM_LOST:
		return "SCTP_COMM_LOST"
	case SCTP_RESTART:
		return "SCTP_RESTART"
	case SCTP_SHUTDOWN_COMP:
		return "SCTP_SHUTDOWN_COMP"
	case SCTP_CANT_STR_ASSOC:
		return "SCTP_CANT_STR_ASSOC"
	default:
		panic(fmt.Sprintf("Unknown SCTPState: %d", s))
	}
}

type SCTPAddressFamily int

const (
	SCTP4 = SCTPAddressFamily(iota)
	SCTP6
	SCTP6Only
)

func (af SCTPAddressFamily) ToSyscall() int {

	switch af {
	case SCTP4:
		return syscall.AF_INET
	case SCTP6:
		return syscall.AF_INET6
	case SCTP6Only:
		return syscall.AF_INET6
	default:
		panic("Invalid SCTPAddressFamily")
	}
}

func (af SCTPAddressFamily) String() string {
	switch af {
	case SCTP4:
		return "ip4"
	case SCTP6:
		return "ip6"
	case SCTP6Only:
		return "ip6"
	default:
		panic("Invalid SCTPAddressFamily")
	}
}

type SCTPSocketMode int

const (
	OneToOne = SCTPSocketMode(iota)
	OneToMany
)

type PeerChangeState uint32

const (
	SCTP_ADDR_AVAILABLE = iota
	SCTP_ADDR_UNREACHABLE
	SCTP_ADDR_REMOVED
	SCTP_ADDR_ADDED
	SCTP_ADDR_MADE_PRIM
)
